### ISSUE TITLE
Create a public build artifact

### ISSUE THREAD

**Issue by aimichal** [allenai/openie-standalone#12]
Make the artifacts of this library available as a maven dependency for public use.

Currently there is an issue with using Bintray and the custom open source license for OpenIE:

https://github.com/allenai/openie-standalone/blob/master/build.sbt#L30-L39

**Comment by lewismc** [comment]
@aimichal I would also really like to see a public artifact available. Are you working on this? If not then maybe I can chip in and help. @Yongyao CC for context.

**Comment by lewismc** [comment]
It would be great to shadow the availability of the previous artifacts at 
http://search.maven.org/#search|gav|1|g%3A%22edu.washington.cs.knowitall.openie%22%20AND%20a%3A%22openie_2.10%22

**Comment by jkinkead** [comment]
I think `v4.2.6` is publicly released on JCenter: https://bintray.com/allenai/maven/org.allenai.openie%3Aopenie_2.11

**Comment by lewismc** [comment]
Cool, I didn't see that. Thank you @jkinkead

**Comment by jkinkead** [comment]
There's also some instructions [towards the bottom of the README](https://github.com/allenai/openie-standalone#hello-world-example).

I'm closing this as fixed.
