### ISSUE TITLE
Missing bintray credentials

### ISSUE THREAD

**Issue by 2gavy** [allenai/openie-standalone#13]
Hello.
I'm facing some credentials problems when I tried to compile the package.

Error: Missing bintray credentials .../.bintray/.credentials. Some bintray features depend on this. 

Steps I’ve taken,

1. I have downloaded the release from GitHub (https://github.com/allenai/openie-standalone/releases).
2. Next, I’ve used Terminal to compile it (sbt compile and sbt package). Both tells me I do not have the necessary credentials.

Hope someone can help. Thank you in advance.

**Comment by jkinkead** [comment]
This is actually just a warning; you can ignore it safely. The plugin for resolving java packages from [Bintray](https://bintray.com/) prints these messages even if it's unused. If you'd like to resolve the errors, you can create a (free) account with Bintray and set up your credentials per the instructions.

Does the project compile correctly otherwise?

**Comment by 2gavy** [comment]
Still unable to compile it. 

Following http://stackoverflow.com/questions/35730020/access-a-bintray-private-repository-via-sbt, I've also created a Bintray account and added all these code into the file but still unable to "sbt package" it. Have attached the error message I encountered.

Thank you for your time.

![screen shot 2017-01-10 at 10 00 10 pm](https://cloud.githubusercontent.com/assets/9292451/21809490/ec0cdf26-d782-11e6-9a51-797199c3c2a5.png)

**Comment by jkinkead** [comment]
Sorry, this is a problem with the our `sbt` configuration. You need to have a `.git` directory present in the root of your project, where you run `sbt` from (where the `build.sbt` file is). Alternately, updating [the plugin version](https://github.com/allenai/openie-standalone/blob/67fcc34913c45475038da860cb0824e5cfe74fc9/project/plugins.sbt#L1) to `1.5.0` should fix this.

**Comment by 2gavy** [comment]
Hi. Have tried the alternate method as suggested by updating the plugin version to 1.5.0. It is able to 'sbt compile' now. I'm trying to 'sbt package' it into a JAR but got the following errors:

![screen shot 2017-01-28 at 1 01 43 pm](https://cloud.githubusercontent.com/assets/9292451/22394371/61a7faa6-e55a-11e6-9d4a-f9d7310667cf.png)

Once again thank you very much.

**Comment by jkinkead** [comment]
It looks like you're running in a detached head state. What does `git status` print on the commandline?

**Comment by 2gavy** [comment]
Hi again. I've managed to solve the problem. The mistake I made was to download the zip file instead of cloning the repository.

To summarise my errors I faced and some findings during the compilation. 

1) Clone the repository.

This should resolve the nonzero exit value errors seen above.

2) Go to project/plugins.sbt and change 

`addSbtPlugin("org.allenai.plugins" % "allenai-sbt-plugins" % "1.4.8")
`

to

`addSbtPlugin("org.allenai.plugins" % "allenai-sbt-plugins" % "1.5.0")
`

This is to solve the missing binary credentials error.

3) Add in

`addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")
`

This line is needed for 'sbt assembly' command when you want a standalone JAR file with all dependencies.

4) Go to the folder directory and enter this command:

`export SBT_OPTS="-XX:MaxMetaspaceSize=1024m -Xms2048m -Xmx20484m"
`

This command is to increase the memory RAM size for the assembly compilation. If you do not enter this command, you will most likely face a memory issue (which will be thrown after [info] Including from cache: log4j-1.2.17.jar).

The files should compile as expected and you will find your standalone JAR file in .../openie-standalone/target/scala-2.11/openie-assembly-_VERSION_-SNAPSHOT.jar

I hope this short guide will help someone in the future.

Thank you @jkinkead for your prompt responses.

**Comment by victoriastuart** [comment]
```
[victoria@victoria openie-standalone]$ sbt

    [info] Loading project definition from /mnt/Vancouver/apps/openie-standalone/project
    Missing bintray credentials /home/victoria/.bintray/.credentials. Some bintray features depend on this.
    [info] Set current project to openie (in build file:/mnt/Vancouver/apps/openie-standalone/)

    > ^c

    ----------------------------------------
    https://github.com/magneticio/vamp/issues/157#event-325131431

    add the following file to your user dir: .bintray/.credentials

        realm = Bintray API Realm
        host = api.bintray.com
        user =
        password =

    Victoria -- I created

        /home/victoria/.bintray/.credentials

    with those lines.
    ----------------------------------------

[victoria@victoria openie-standalone]$ sbt

    [info] Loading project definition from /mnt/Vancouver/apps/openie-standalone/project
    [info] Set current project to openie (in build file:/mnt/Vancouver/apps/openie-standalone/)
    >
```
