### ISSUE TITLE
Testing before building

### ISSUE THREAD

**Issue by Achilles-96** [allenai/openie-standalone#19]
Is there a live demo where we can test it for some sample sentences before going through building it. An api is also fine.

**Comment by jkinkead** [comment]
The closest we have is [the search page](http://openie.allenai.org/).

**Comment by Achilles-96** [comment]
Can you provide output for the first example sentence in README - ``The U.S. president Barack Obama gave his speech on Tuesday to thousands of people.``

**Comment by Achilles-96** [comment]
Building is straightforward. I thought I will have dependency problems. Thanks.
