### ISSUE TITLE
REST API for openie

### ISSUE THREAD

**Issue by lewismc** [allenai/openie-standalone#22]
Hi @aimichal @schmmd @jkinkead @ansjin @ColinArenz I am interested in running OpenIE as a service e.g. such that I can pass data to some remote endpoint which then kicks off an extraction and returns the result.
The one question I have right now... is this currently possible? I've looked over the source code and can't see any endpoints available. Can someone clarify before I embark on this?
Additionally, is anyone able to chime in on which Webservices framework they would like to see working with OpenIE? I came across [scalatra](https://github.com/scalatra/scalatra) which looks ideal... however I want to use something which has support of you guys.
Thanks, 
Lewis

**Comment by lewismc** [comment]
Additionally, I am looking to prevent the models from loading every time I wish to undertake an extraction. Do you have any suggestions for achieving this? Thanks.

**Comment by ckarenz** [comment]
We don't currently offer an REST endpoint, but this is something we've considered internally due to OpenIE's heavy memory footprint.

We're actively moving other services over to Scalatra (moving away from Spray), so that would be an excellent choice if you'd like to take this work on.

**Comment by lewismc** [comment]
Hi @ColinArenz OK doke. I'll try my best to begin work on this over the weekend. I'll keep my comments coming here. Thanks for replying. We are looking to enable an HTTP-accessible OpenIE service such that I can stream extractions there and get our results back.

**Comment by amandalmia14** [comment]
@lewismc have you able to do it ? OpenIE as Service?

**Comment by amandalmia14** [comment]
@ckarenz Well I am also facing the same issue where I need to get the triples from 1K files and i don't want to reload the jar everytime.  Is there any workaround?

**Comment by lewismc** [comment]
@amandalmia14 no there is no workaround. The way to address this is to write in the REST API using scalatra or some other framework. I never got around to it and this is not a priority for me any more so I will not be writing the code this time around... sorry about that folks.

**Comment by aimichal** [comment]
I'm closing this now, as there's no solution available.

If something surfaces then it'll be mentioned in the docs of this repo.
