### ISSUE TITLE
[may be resolved, hold until further notice] Errors running sbt scripts

### ISSUE THREAD

**Issue by collin** [allenai/openie-standalone#23]
# The error
When runing the usage command:

```bash
sbt "runMain edu.knowitall.openie.OpenIECli --usage"
```

I get the following error:

```bash
java.lang.RuntimeException: Setting value cannot be null: {file:/app/openie-standalone/}/*:gitCurrentBranch
	at scala.sys.package$.error(package.scala:27)
	at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] Setting value cannot be null: {file:/app/openie-standalone/}/*:gitCurrentBranch
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] Expected ID character
[error] Not a valid command: runMain
[error] runMain edu.knowitall.openie.OpenIECli --usage
[error]        ^
```
Looks like there are two potential errors there, I'm not sure if they are connected or individual errors

### 1
```
[error] Setting value cannot be null: {file:/app/openie-standalone/}/*:gitCurrentBranch
```

### 2
```
[error] Expected ID character
[error] Not a valid command: runMain
[error] runMain edu.knowitall.openie.OpenIECli --usage
[error]        ^
```

# Steps to reproduce
If you have a docker runtime I have a `Dockerfile`, `docker-compose.yml` and  shell steps to reproduce available in this gist: https://gist.github.com/collin/0062ff9d2ca3bc0f989f8113bfbba235

Any assistance would be greatly appreciated. My object in using openie is to insert nodes and edges into a Neo4J Graph database to see what sort of interesting queries I can run from there. The documents I intend to process are news articles covering current events.

**Comment by collin** [comment]
Looks like #13 might help, I'll look into that.

**Comment by jkinkead** [comment]
Yes, #13 mentions this issue as well: You must have a valid git repository at the project root in order for it to run. Using `git clone` to check this project out solves that, as does running `git init` in the project root & adding an initial commit.

Your second issue stems from ignoring the project load error.
