### ISSUE TITLE
Output file argument is throwing an error

### ISSUE THREAD

**Issue by praneethganta** [allenai/openie-standalone#25]
Output format arugument --ouput-file is not working. It says the file is not found.
PFB the screenshot of the error. Am i doing something wrong?
![output](https://cloud.githubusercontent.com/assets/21272259/24626305/af73310e-1865-11e7-9fc4-07ec9fa58c70.png)

Thank you.

**Comment by bhadramani** [comment]
You may use absolute path.

**Comment by aimichal** [comment]
praneethganta, the argument had a typo. It was `--ouput-file`, but you specified `--output-file`.

A few days after you submitted this issue, this typo was corrected: https://github.com/allenai/openie-standalone/commit/688d099730fef06ea99567cc5bcd84bfe60048da

The latest version supports both args (for backwards compat, I guess), so you should be okay now.
