### ISSUE TITLE
java.lang.NoClassDefFoundError: com/clearnlp/nlp/NLPGetter

### ISSUE THREAD

**Issue by jeffrschneider** [allenai/openie-standalone#26]
I'm trying to run OpenIE from a Java application. 
The install seemed to work properly, and I was able to run it in 'standalone mode' successfully. 

However, when I use the Java starter file, located here:
https://github.com/OpenIE-HelperCodes/OpenIEDemo1/blob/master/src/runner/RunMe.java
it isn't working. Specifically, it's not finding a class:
Exception in thread "main" java.lang.NoClassDefFoundError: com/clearnlp/nlp/NLPGetter
	at edu.knowitall.tool.srl.ClearSrl.<init>(ClearSrl.scala:37)

Any insights, or things I should be checking? 
Jeff

**Comment by jkinkead** [comment]
You should file an issue with OpenIE HelperCodes. That's unaffiliated with this project.

**Comment by jeffrschneider** [comment]
Jesse - 
All that I'm trying to do is use your software in Java. Are you truly unable to help me use your allenai/openie-standalone? This seems really odd... 
Jeff

**Comment by jkinkead** [comment]
We didn't write and don't maintain the package you linked to above, and don't support a Java API currently.
