### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by david942j** [allenai/openie-standalone#30]
Hi openie authors,
thanks for this great work!
I have a question that which paper(s) should I cite if I use this project?

I know there're publications listed [here](http://openie.allenai.org/).
While the readme in this repo says this work is a successor to Ollie, should I cite Ollie (EMNLP 2012), or the latest work such as RelNoun 2.2?

Thanks again :)

**Comment by schmmd** [comment]
You can cite the Ollie paper.  Sorry, there's no ideal publication!

**Comment by david942j** [comment]
Thanks!
