### ISSUE TITLE
Open IE for python

### ISSUE THREAD

**Issue by liu357592109** [allenai/openie-standalone#31]
Hi, 
Does this software have Python wrapper? Or is there any suggest method to call the functions from Python?
Thanks!

**Comment by rupsaijna** [comment]
Try using os.system to trigger running of OpenIE
___________________________________________________________________
e.g.
```python
import os
os.system("sbt 'runMain edu.knowitall.openie.OpenIECli --input-file input.txt --ouput-file openie_output.txt -s'")
output_of_openie=open('openie_output.txt','r').read()
```
_______________________________________________________________

however, for this to work, you will need to first be inside your Openie path, then run your python code from there

**Comment by aimichal** [comment]
Indeed there's no python wrapper for OpenIE.

Perhaps you can split your workflow into stages: generate the sentences to feed into OpenIE, and write them to a file; run OpenIE on those sentences and collect results into another file; finally, read the resulting extractions. If this works for your situation, then a nice side-effect is that you'll have the extractions available for subsequent usage without having to re-run OpenIE.
