### ISSUE TITLE
how to get the certain parts gained from OpenIE and is there any documents  described the format of the results?

### ISSUE THREAD

**Issue by githubg0** [allenai/openie-standalone#32]
Hi. I use the OpenIE to extract triples, and I got the results like:
0.93 (U.S. President Obama; gave; a speech)
if I only want the certain part of the reuslt, like U.S. President Obama, how could I extract this parts?
I tried to find some documents describe the results' format, but I did not find. can some people help me?

**Comment by bhadramani** [comment]
OpenIE does not have such a flexibility. you may process the output your own, in real time or post processing.

**Comment by aimichal** [comment]
githubg0, you can write Scala code to read from the internal datastructures. For an example, see the function `exampleUsage3` at https://github.com/allenai/openie-standalone.

Otherwise you'll have to parse the results yourself outside of Scala.
